// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CrudTask.DAL.Data.Entites;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CrudTask.DAL.Data.Entites.Configurations
{
    public partial class EmployeeConfiguration : IEntityTypeConfiguration<Employee>
    {
        public void Configure(EntityTypeBuilder<Employee> entity)
        {
            entity.Property(e => e.EmployeeId)
                .HasMaxLength(14)
                .IsUnicode(false)
                .HasColumnName("EmployeeID");

            entity.Property(e => e.CityId).HasColumnName("CityID");

            entity.Property(e => e.IsDeleted).HasDefaultValueSql("((0))");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.Salary).HasColumnType("decimal(8, 2)");

            entity.Property(e => e.SubCityId).HasColumnName("SubCityID");

            entity.Property(e => e.VillageId).HasColumnName("VillageID");

            entity.HasOne(d => d.City)
                .WithMany(p => p.Employees)
                .HasForeignKey(d => d.CityId)
                .HasConstraintName("FK__Employees__CityI__52593CB8");

            entity.HasOne(d => d.SubCity)
                .WithMany(p => p.Employees)
                .HasForeignKey(d => d.SubCityId)
                .HasConstraintName("FK__Employees__SubCi__534D60F1");

            entity.HasOne(d => d.Village)
                .WithMany(p => p.Employees)
                .HasForeignKey(d => d.VillageId)
                .HasConstraintName("FK__Employees__Villa__5441852A");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Employee> entity);
    }
}
