// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CrudTask.DAL.Data.Entites;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CrudTask.DAL.Data.Entites.Configurations
{
    public partial class SubCityConfiguration : IEntityTypeConfiguration<SubCity>
    {
        public void Configure(EntityTypeBuilder<SubCity> entity)
        {
            entity.Property(e => e.SubCityId).HasColumnName("SubCityID");

            entity.Property(e => e.CityId).HasColumnName("CityID");

            entity.Property(e => e.SubCityName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.City)
                .WithMany(p => p.SubCities)
                .HasForeignKey(d => d.CityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SubCities__CityI__4AB81AF0");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SubCity> entity);
    }
}
