// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrudTask.DAL.Data.Entites
{
    public partial class City
    {
        public City()
        {
            Employees = new HashSet<Employee>();
            SubCities = new HashSet<SubCity>();
        }

        public int CityId { get; set; }
        public string CityName { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<SubCity> SubCities { get; set; }
    }
}