// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrudTask.DAL.Data.Entites
{
    public partial class Employee
    {
        public string EmployeeId { get; set; }
        public string Name { get; set; }
        public decimal? Salary { get; set; }
        public int? CityId { get; set; }
        public int? SubCityId { get; set; }
        public int? VillageId { get; set; }
        public bool? IsDeleted { get; set; } = false;

        public virtual City City { get; set; }
        public virtual SubCity SubCity { get; set; }
        public virtual Village Village { get; set; }
    }
}