// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrudTask.DAL.Data.Entites
{
    public partial class SubCity
    {
        public SubCity()
        {
            Employees = new HashSet<Employee>();
            Villages = new HashSet<Village>();
        }

        public int SubCityId { get; set; }
        public string SubCityName { get; set; }
        public int CityId { get; set; }

        public virtual City City { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Village> Villages { get; set; }
    }
}