// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrudTask.DAL.Data.Entites
{
    public partial class Village
    {
        public Village()
        {
            Employees = new HashSet<Employee>();
        }

        public int VillageId { get; set; }
        public string VillageName { get; set; }
        public int SubCityId { get; set; }

        public virtual SubCity SubCity { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}